/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'secondary-fixed': '#d3e4fe',
        'surface-container-low': '#f2f3ff',
        'on-surface-variant': '#424656',
        'secondary-container': '#d0e1fb',
        'tertiary-container': '#cc4204',
        'surface-container': '#ecedfa',
        'primary-container': '#0066ff',
        'on-primary-fixed-variant': '#003fa4',
        'secondary-fixed-dim': '#b7c8e1',
        'tertiary-fixed': '#ffdbd0',
        'tertiary-fixed-dim': '#ffb59d',
        'on-tertiary-container': '#fff6f4',
        'on-tertiary-fixed': '#390c00',
        'surface-tint': '#0054d6',
        surface: '#faf8ff',
        'on-background': '#191b24',
        'surface-dim': '#d8d9e6',
        'on-error-container': '#93000a',
        'on-secondary-container': '#54647a',
        tertiary: '#a33200',
        error: '#ba1a1a',
        'outline-variant': '#c2c6d8',
        primary: '#0050cb',
        'surface-container-lowest': '#ffffff',
        'on-secondary': '#ffffff',
        'surface-variant': '#e1e2ee',
        'on-primary-container': '#f8f7ff',
        'on-primary': '#ffffff',
        background: '#faf8ff',
        'error-container': '#ffdad6',
        'on-tertiary': '#ffffff',
        'surface-container-highest': '#e1e2ee',
        'surface-bright': '#faf8ff',
        'on-secondary-fixed': '#0b1c30',
        'inverse-surface': '#2e303a',
        'inverse-on-surface': '#eff0fd',
        'primary-fixed': '#dae1ff',
        'on-surface': '#191b24',
        outline: '#727687',
        'on-primary-fixed': '#001849',
        secondary: '#505f76',
        'on-secondary-fixed-variant': '#38485d',
        'inverse-primary': '#b3c5ff',
        'primary-fixed-dim': '#b3c5ff',
        'on-error': '#ffffff',
        'surface-container-high': '#e6e7f4',
        'on-tertiary-fixed-variant': '#832600',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        base: '4px',
        gutter: '24px',
        xl: '32px',
        margin: '32px',
        lg: '24px',
        xs: '4px',
        sm: '8px',
        md: '16px',
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'label-bold': ['12px', { lineHeight: '1', letterSpacing: '0.05em', fontWeight: '600' }],
        h3: ['20px', { lineHeight: '1.4', letterSpacing: '-0.01em', fontWeight: '600' }],
        'body-lg': ['16px', { lineHeight: '1.6', letterSpacing: '0', fontWeight: '400' }],
        h2: ['24px', { lineHeight: '1.3', letterSpacing: '-0.01em', fontWeight: '600' }],
        h1: ['36px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '700' }],
        'label-md': ['12px', { lineHeight: '1', letterSpacing: '0', fontWeight: '500' }],
        'body-md': ['14px', { lineHeight: '1.5', letterSpacing: '0', fontWeight: '400' }],
      },
    },
  },
  plugins: [],
}
